USE hbnb_dev_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS amenities;
DROP TABLE IF EXISTS cities;
DROP TABLE IF EXISTS place_amenity;
DROP TABLE IF EXISTS places;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS states;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;

