#!/usr/bin/env bash
# Install Fabric for Python 3 - version 1.14.post1

pip3 uninstall Fabric
sudo apt-get install libffi-dev -y
sudo apt-get install libssl-dev -y
sudo apt-get install build-essential -y
sudo apt-get install python3.4-dev -y
sudo apt-get install libpython3-dev -y
pip3 install pyparsing -y
pip3 install appdirs -y
pip3 install setuptools==40.1.0 -y
pip3 install cryptography==2.8 -y
pip3 install bcrypt==3.1.7 -y
pip3 install PyNaCl==1.3.0 -y
pip3 install Fabric3==1.14.post1 -y
