#!/bin/bash
git add .
echo "Type in commit message: "
read message
git commit -m "$message"
git push --set-upstream origin kings-branch
echo "==================================DONE================================="
