#!/usr/bin/env bash
# To take 4 parameters to transfer a file from our client to a server
if [ $# -lt 3 ]; then
    echo 'Usage: ./transfer PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
    exit 1
fi
scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/$1"
