#!/usr/bin/env bash
# Checking for command-line argument
if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assigning Arguments to variables

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4
user="ubuntu"
key="~/.ssh/school"

# Disabbling Strict Host Key checking
scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# Checking if the transfer was successful
if [ $? -eq 0 ]
then
  echo "FILE TRANSFER WAS SUCCESSFULL"
else
  echo "FILE TRANSFER FAILED"
fi
