#!/bin/bash
# make SURE TO RUN WITH source
# source ./tests/setup_env_for_tests
# script to setup env vars for testing dbstorage
export HBNB_MYSQL_USER=hbnb_test
export HBNB_MYSQL_PWD=hbnb_test_pwd
export HBNB_MYSQL_HOST=localhost
export HBNB_MYSQL_DB=hbnb_test_db
export HBNB_TYPE_STORAGE=db
export HBNB_ENV=test
