#!/bin/env bash


autopep8 . --recursive --aggressive --in-place --pep8-passes 2000 --verbose
pycodestyle --show-source --show-pep8 models/*.py
pycodestyle --show-source --show-pep8 *.py
pycodestyle --show-source --show-pep8 tests/*.py

if [ "$?" == "0" ]; then
    push "$1"
fi
