#!/usr/bin/env bash

# Exit immediately if a command returns a non-zero status
set -e

# Define the directory where the script is located
SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Define the root directory of the repository using the "git" command
ROOTDIR="$(git -C "$SCRIPTDIR" rev-parse --show-toplevel)"

# Debugging output for the above defined variables
set -x

# Write the content to the file "AUTHORS" in the root directory
cat > "${ROOTDIR}/CONTRIBUTORS" <<- EOF
# File generated by utils/contributors.sh. Do not edit.
# This file lists all contributors to the repository.
# See utils/contributors.sh to make modifications.

$(git -C "$ROOTDIR" log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf)
EOF
